'use client';
import {useEffect,useState} from 'react';
import {UserPlus,Copy,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Row={id:string;login_id:string;display_name:string;role:string;active:number;must_change:number};
export default function Operators(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[id,setId]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[issued,setIssued]=useState<{loginId:string;temporaryPassword:string}|null>(null),[copied,setCopied]=useState(false),[confirm,setConfirm]=useState<{row:Row;action:string}|null>(null);
 async function refresh(){try{const r=await fetch('/api/operators',{cache:'no-store'});if(!r.ok)throw Error('担当者を読み込めませんでした。');setRows(await r.json() as Row[])}catch(e){setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{refresh()},[]);
 async function act(action:string,row?:Row){setBusy(true);setError('');try{const r=await fetch('/api/operators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:row?.id,loginId:id,name})});const d=await r.json() as {error?:string;loginId:string;temporaryPassword?:string};if(!r.ok)throw Error(d.error||'更新できませんでした。');if(d.temporaryPassword){setIssued({loginId:d.loginId,temporaryPassword:d.temporaryPassword});setCopied(false)}if(action==='create'){setId('');setName('')}await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="operator-management"><a href="/admin" className="back-link">← イベント・質問の管理へ</a><span className="eyebrow">TEAM</span><h1>担当者の管理</h1><p>担当者ごとに運営IDを発行します。メールアドレスは不要です。</p><section className="team-create"><h2><UserPlus size={22}/>担当者を追加</h2><form onSubmit={e=>{e.preventDefault();act('create')}}><label>表示名<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required placeholder="例：山田さん" disabled={busy}/></label><label>運営ID<input value={id} onChange={e=>setId(e.target.value)} pattern="[a-zA-Z0-9_-]{3,40}" minLength={3} maxLength={40} autoCapitalize="none" spellCheck={false} required placeholder="例：yamada" disabled={busy}/></label><button className="primary" disabled={busy}>{busy?'処理中…':'IDを発行'}</button></form><p className="analysis-note">IDは半角英数字・ハイフン・アンダーバー3〜40文字。大文字は小文字として扱います。</p></section><p role="alert" className="status">{error}</p><section aria-label="担当者一覧" className="team-list">{loading?<p>読み込み中…</p>:rows.map(row=><article key={row.id}><div><h2>{row.display_name}</h2><span className="team-id">{row.login_id}</span><span className="team-badge">{row.role==='owner'?'運営責任者':!row.active?'利用停止中':row.must_change?'初回変更待ち':'利用中'}</span></div>{row.role!=='owner'?<div className="team-actions"><button disabled={busy} onClick={()=>setConfirm({row,action:'reset'})}>仮パスワード再発行</button><button disabled={busy} onClick={()=>setConfirm({row,action:row.active?'disable':'enable'})}>{row.active?'利用停止':'利用を再開'}</button></div>:<a href="/admin/password">パスワード変更</a>}</article>)}</section>
 <Dialog open={!!issued} onOpenChange={open=>{if(!open)setIssued(null)}}><DialogContent className="credential-dialog"><DialogHeader><DialogTitle>ログイン情報を発行しました</DialogTitle><DialogDescription>この仮パスワードは、この画面で一度だけ表示します。本人へ個別にお渡しください。初回ログイン時に変更が必要です。</DialogDescription></DialogHeader><dl><dt>運営ID</dt><dd>{issued?.loginId}</dd><dt>仮パスワード</dt><dd>{issued?.temporaryPassword}</dd></dl><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(`運営用ページ：${location.origin}/admin\n運営ID：${issued?.loginId}\n仮パスワード：${issued?.temporaryPassword}\n初回ログイン後にパスワードを変更してください。`);setCopied(true)}catch{setError('コピーできませんでした。手動で控えてください。')}}}>{copied?<Check size={18}/>:<Copy size={18}/>} {copied?'コピーしました':'ログイン情報をコピー'}</button></DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.row.display_name}さんの{confirm?.action==='reset'?'仮パスワードを再発行しますか？':confirm?.action==='disable'?'利用を停止しますか？':'利用を再開しますか？'}</AlertDialogTitle><AlertDialogDescription>{confirm?.action==='reset'?'現在のパスワードは使えなくなり、ログイン中の端末もログアウトされます。':confirm?.action==='disable'?'ログイン中の端末もログアウトされ、イベント・質問を閲覧できなくなります。':'この担当者が再びログインできるようになります。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction onClick={()=>{if(confirm)act(confirm.action,confirm.row)}}>実行する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
