import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {SourceTextModule,SyntheticModule,createContext} from 'node:vm';
import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import ts from 'typescript';
import {webcrypto,scryptSync,timingSafeEqual} from 'node:crypto';
import {Buffer} from 'node:buffer';

async function fixture(){
 const sql=new DatabaseSync(':memory:');for(const name of ['0000_third_the_hand','0001_ancient_lady_deathstrike','0002_skinny_lake','0003_moaning_ben_urich'])sql.exec(readFileSync('drizzle/'+name+'.sql','utf8'));
 const db={prepare(query){const bind=(...args)=>({async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:sql.prepare(query).run(...args)}}});return {...bind(),bind}},async batch(statements){sql.exec('BEGIN');try{const r=[];for(const stmt of statements)r.push(await stmt.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
 const jar=new Map(),cookieWrites=[];const env={DB:db};
 const context=createContext({console,Request,Response,Headers,URL,TextEncoder,TextDecoder,Uint8Array,crypto:webcrypto,AbortSignal,Date,JSON,Error,Promise,setTimeout,clearTimeout});
 const cache=new Map();
 function synthetic(name,values){const m=new SyntheticModule(Object.keys(values),function(){for(const [k,v] of Object.entries(values))this.setExport(k,v)},{context,identifier:name});cache.set(name,m);return m}
 synthetic('cloudflare:workers',{env});synthetic('next/headers',{cookies:async()=>({get:name=>jar.has(name)?{value:jar.get(name)}:undefined,set(name,value,options){cookieWrites.push({name,value,options});if(options.maxAge===0)jar.delete(name);else jar.set(name,value)}}),headers:async()=>new Headers()});
 synthetic('next/navigation',{redirect(){throw Error('Unexpected redirect')}});synthetic('node:crypto',{scryptSync,timingSafeEqual});synthetic('node:buffer',{Buffer});
 async function load(name,parent=resolve('index.ts')){if(cache.has(name))return cache.get(name);let file=name.startsWith('@/')?resolve(name.slice(2)):resolve(dirname(parent),name);if(!file.endsWith('.ts'))file+='.ts';if(cache.has(file))return cache.get(file);const code=ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const m=new SourceTextModule(code,{context,identifier:file});cache.set(file,m);await m.link((specifier,ref)=>load(specifier,ref.identifier));return m}
 async function module(path){const m=await load(path);if(m.status==='linked')await m.evaluate();return m.namespace}
 const route=await module('@/app/api/auth/password/route'),server=await module('@/lib/server'),auth=await module('@/lib/password-auth'),team=await module('@/app/api/operators/route'),questions=await module('@/app/api/admin/route'),events=await module('@/app/api/events/route'),oldEmail=await module('@/app/api/auth/email/verify/route');
 env.INITIAL_OPERATOR_HASH=auth.hashPassword('initial-test-password-123');
 const req=(data,origin='https://question.test')=>new Request('https://question.test/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,'cf-connecting-ip':'192.0.2.10'},body:JSON.stringify(data)});
 const login=(loginId='mga-owner',password='initial-test-password-123')=>route.POST(req({action:'login',loginId,password}));
 const change=(currentPassword='initial-test-password-123',password='my-personal-password-456')=>route.POST(req({action:'change',currentPassword,password}));
 return {sql,env,jar,cookieWrites,route,server,auth,team,questions,events,oldEmail,req,login,change};
}
test('first login requires password change; hashed cookie and logout revoke access',async()=>{const f=await fixture();assert.equal((await f.login()).status,200);assert.equal(await f.server.admin(),null);assert.equal((await f.questions.GET(new Request('https://question.test/api/admin'))).status,403);assert.equal((await f.change()).status,200);assert.equal((await f.server.admin()).role,'owner');const saved=f.jar.get(f.auth.operatorCookie);assert.match(saved,/^[a-f0-9]{64}$/);assert.notEqual(f.sql.prepare('SELECT token_hash FROM operator_sessions').get().token_hash,saved);const cookie=f.cookieWrites[0];assert.ok(cookie.options.httpOnly&&cookie.options.secure);assert.equal(cookie.options.sameSite,'strict');await f.route.POST(f.req({action:'logout'}));f.jar.set(f.auth.operatorCookie,saved);assert.equal(await f.server.admin(),null);assert.equal((await f.login()).status,401)});
test('unknown ID, wrong password, old email auth, CSRF and account guessing fail closed',async()=>{const f=await fixture();assert.equal((await f.login('missing')).status,401);assert.equal((await f.login('mga-owner','wrong')).status,401);assert.equal((await f.route.POST(f.req({action:'login',loginId:'mga-owner',password:'initial-test-password-123'},'https://evil.test'))).status,400);assert.equal((await f.oldEmail.POST(f.req({code:'123456'}))).status,410);for(let n=0;n<9;n++)assert.equal((await f.login('mga-owner','wrong')).status,401);assert.equal((await f.login()).status,429);assert.equal(await f.server.admin(),null);assert.equal((await f.events.POST(f.req({title:'unauthorized',date:'',open:1}))).status,403);assert.equal((await f.team.GET()).status,403)});
test('operator creation, roles, reset and disable revoke sessions immediately',async()=>{const f=await fixture();await f.login();await f.change();const ownerCookie=f.jar.get(f.auth.operatorCookie);const created=await f.team.POST(f.req({action:'create',loginId:'Staff-01',name:'担当者'}));assert.equal(created.status,200);const d=await created.json();assert.equal(d.loginId,'staff-01');assert.ok(d.temporaryPassword.length>=20);const row=f.sql.prepare("SELECT * FROM operators WHERE login_id='staff-01'").get();assert.ok(!row.password_hash.includes(d.temporaryPassword));f.jar.clear();assert.equal((await f.login('staff-01',d.temporaryPassword)).status,200);assert.equal(await f.server.admin(),null);assert.equal((await f.change(d.temporaryPassword,'staff-personal-pass-789')).status,200);assert.equal((await f.server.admin()).role,'operator');assert.equal((await f.team.GET()).status,403);assert.equal((await f.team.POST(f.req({action:'create',loginId:'attacker',name:'x'}))).status,403);const staffCookie=f.jar.get(f.auth.operatorCookie);f.jar.set(f.auth.operatorCookie,ownerCookie);assert.equal((await f.team.POST(f.req({action:'disable',id:row.id}))).status,200);f.jar.set(f.auth.operatorCookie,staffCookie);assert.equal(await f.server.admin(),null);assert.equal((await f.login('staff-01','staff-personal-pass-789')).status,401);f.jar.set(f.auth.operatorCookie,ownerCookie);await f.team.POST(f.req({action:'enable',id:row.id}));const reset=await f.team.POST(f.req({action:'reset',id:row.id}));const fresh=await reset.json();assert.equal((await f.login('staff-01','staff-personal-pass-789')).status,401);f.jar.clear();assert.equal((await f.login('staff-01',fresh.temporaryPassword)).status,200);assert.equal(await f.server.admin(),null);f.jar.set(f.auth.operatorCookie,ownerCookie);assert.equal((await f.team.POST(f.req({action:'disable',id:'initial-owner'}))).status,400)});
test('forged, expired and stale credential sessions cannot authorize; missing bootstrap cannot create owner',async()=>{const f=await fixture();f.env.INITIAL_OPERATOR_HASH='';assert.equal((await f.login()).status,401);assert.equal(f.sql.prepare('SELECT count(*) AS n FROM operators').get().n,0);f.env.INITIAL_OPERATOR_HASH=f.auth.hashPassword('initial-test-password-123');await f.login();await f.change();const real=f.jar.get(f.auth.operatorCookie);f.jar.set(f.auth.operatorCookie,'a'.repeat(64));assert.equal(await f.server.admin(),null);f.jar.set(f.auth.operatorCookie,real);f.sql.exec('UPDATE operator_sessions SET expires_at=0');assert.equal(await f.server.admin(),null);await f.login('mga-owner','my-personal-password-456');f.sql.exec('UPDATE operators SET version=version+1');assert.equal(await f.server.admin(),null)});
