import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const questions=sqliteTable('questions',{id:text('id').primaryKey(),eventId:text('event_id'),body:text('body').notNull(),category:text('category').notNull(),source:text('source').notNull(),status:text('status').notNull().default('pending'),answer:text('answer').notNull().default(''),createdAt:integer('created_at').notNull()},t=>[index('questions_status_created').on(t.eventId,t.status,t.createdAt)]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),questionId:text('question_id').notNull(),createdAt:integer('created_at').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),title:text('title').notNull(),date:text('date').notNull().default(''),open:integer('open').notNull().default(1),createdAt:integer('created_at').notNull()});
export const adminChallenges=sqliteTable('admin_challenges',{tokenHash:text('token_hash').primaryKey(),email:text('email').notNull(),expiresAt:integer('expires_at').notNull(),attempts:integer('attempts').notNull().default(0)});
export const adminSessions=sqliteTable('admin_sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull(),email:text('email').notNull(),expiresAt:integer('expires_at').notNull()});

export const operators=sqliteTable('operators',{id:text('id').primaryKey(),loginId:text('login_id').notNull().unique(),displayName:text('display_name').notNull(),passwordHash:text('password_hash').notNull(),role:text('role').notNull().default('operator'),active:integer('active').notNull().default(1),mustChange:integer('must_change').notNull().default(1),version:integer('version').notNull().default(1),createdAt:integer('created_at').notNull()});
export const operatorSessions=sqliteTable('operator_sessions',{tokenHash:text('token_hash').primaryKey(),operatorId:text('operator_id').notNull().references(()=>operators.id),version:integer('version').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('operator_sessions_operator').on(t.operatorId)]);
