'use client';
import {useState} from 'react';
import {LockKeyhole,ArrowRight,Eye,EyeOff} from 'lucide-react';
async function authAction(data:Record<string,string>){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:controller.signal});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'処理できませんでした。')}catch(e){if(controller.signal.aborted)throw Error('応答に時間がかかっています。ページを再読み込みして、ログイン状態を確認してください。');if(e instanceof TypeError)throw Error('接続できませんでした。時間をおいて再度お試しください。');throw e}finally{clearTimeout(timer)}}
export default function PasswordLogin({change=false,required=false}:{change?:boolean;required?:boolean}){const[id,setId]=useState(''),[password,setPassword]=useState(''),[current,setCurrent]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setMessage('');if(change&&password!==confirm){setMessage('新しいパスワードと確認用の入力が一致しません。');return}setBusy(true);try{await authAction(change?{action:'change',currentPassword:current,password}:{action:'login',loginId:id,password});setPassword('');setCurrent('');setConfirm('');location.assign('/admin')}catch(e){setMessage((e as Error).message);setBusy(false)}}
 return <main className="operator-entry email-entry password-entry"><div className="auth-emblem"><LockKeyhole size={28}/></div><span className="eyebrow">STAFF ONLY</span><h1>{change?'パスワードを変更':'運営用ログイン'}</h1><p>{change?(required?'初回ログインです。仮パスワードを、ご自身だけが知っているパスワードへ変更してください。':'新しいパスワードを設定します。ほかの端末からはログアウトされます。'):'発行された運営IDとパスワードを入力してください。'}</p><form onSubmit={submit}>
 {change?<><label htmlFor="current-password">{required?'仮パスワード':'現在のパスワード'}</label><input id="current-password" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} maxLength={128} required disabled={busy}/></>:<><label htmlFor="operator-id">運営ID</label><input id="operator-id" autoComplete="username" autoCapitalize="none" spellCheck={false} value={id} onChange={e=>setId(e.target.value)} maxLength={40} required disabled={busy} placeholder="例：mga-owner"/></>}
 <label htmlFor="operator-password">{change?'新しいパスワード':'パスワード'}</label><div className="password-field"><input id="operator-password" type={show?'text':'password'} autoComplete={change?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={change?15:undefined} maxLength={128} required disabled={busy}/><button type="button" aria-label={show?'パスワードを隠す':'パスワードを表示'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>
 {change&&<><p className="analysis-note">15〜128文字。長いフレーズも使用できます。</p><label htmlFor="confirm-password">新しいパスワード（確認）</label><input id="confirm-password" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={15} maxLength={128} required disabled={busy}/></>}
 <p role="alert" className="status">{message}</p><button className="primary full" disabled={busy}>{busy?'確認中…':change?'変更して運営画面へ':'ログイン'}<ArrowRight size={18}/></button></form>
 {!change&&<p className="auth-help">IDの発行やパスワードの再発行は、運営責任者にご依頼ください。</p>}{change&&!required&&<a className="entry-visitor" href="/admin">運営画面に戻る</a>}{change&&required&&<PasswordLogout/>}<a className="entry-visitor" href="/">来場者用ページへ →</a></main>
}
export function PasswordLogout(){const[busy,setBusy]=useState(false),[message,setMessage]=useState('');return <div><button disabled={busy} onClick={async()=>{setBusy(true);try{await authAction({action:'logout'});location.assign('/admin')}catch{setMessage('ログアウトできませんでした。');setBusy(false)}}}>{busy?'ログアウト中…':'ログアウト'}</button><span role="status">{message}</span></div>}
